server:
  port: 9529
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_center?serverTimezone=Asia/Shanghai
    hikari:
      username: root
      password: 123
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        #nocas服务地址
        server-addr: localhost:8848
        cluster-name: CD
#        namespace: 5e1a5808-ee55-46c9-929c-22a0af9f4bf7
  #        metadata:
#          version: v1
#          target-version: v1
  application:
    # 服务名称
    name: user-center

#  mybatis.mapper-locations=classpath:mapper/*/*.xml
#  logging.level.com.shanrong.yuefou.dao=debug
mybatis:
  mapper-locations: classpath:mapper/*.xml

