server:
  port: 9526
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/content_center?serverTimezone=Asia/Shanghai
    hikari:
      username: root
      password: 123
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        #nocas服务地址
        server-addr: localhost:8848
        # 指定命名空间
        # namespace: 5e1a5808-ee55-46c9-929c-22a0af9f4bf7
        # 指定集群名称
        cluster-name: YL
        metadata:
          # 本身版本
          version: v1
          # 可调用服务实例版本
          target-version: v1
    sentinel:
      transport:
#        指定sentinel控制台的地址
        dashboard: localhost:8080
  main:
    allow-bean-definition-overriding: true
  application:
    name: content-center


#  mybatis.mapper-locations=classpath:mapper/*/*.xml
#  logging.level.com.shanrong.yuefou.dao=debug
mybatis:
  mapper-locations: classpath:mapper/*.xml

#Ribbon规则配置
user-center:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

#Ribbon饥饿加载
ribbon:
  eager-load:
    enabled: true
    clients: user-center

#日志打印设置
#logging:
#  level:
#    com.ym.content.config.feign.UserCenterFeignClient: debug
feign:
  client:
    config:
      # 全局配置
      default:
        loggerLevel: full
        #        单独配置
        #      user-center:
        #        loggerLevel: full
  httpclient:
#    让feign使用apache httpclient做请求；而不是默认的urlconnection
    enabled: true
#    feign最大连接数
    max-connections: 200
#    feign单个路径的最大连接数
    max-connections-per-route: 50
#配置sentinel
management:
  endpoints:
    web:
      exposure:
        include: '*'


